# Generated by Selenium IDE
import unittest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1222(unittest.TestCase):
  def setup(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_1222(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.set_window_size(1037, 1037)
    self.driver.find_element(By.ID, "kw").click()
    self.driver.find_element(By.ID, "kw").click()
    self.driver.find_element(By.ID, "kw").send_keys("三十而已")
    self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.ID, "result_logo")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "wrapper_wrapper").click()
    time.sleep(6)
  if __name__=="__main__":
    unittest.main()
